### ISSUE TITLE
Thunderbird 91.2 filter applying failed

### ISSUE THREAD

**Issue by morda666** [kgraefe/thunderbird-autotag#1]
Hello Kondrad,

your autotag dosn't work with Thunderbird 91.2 and FiltaQuilla 3.2. Can you test it please?
I can't live without it ;)

Thanks.

Jozef

**Comment by kgraefe** [comment]
I will when I get to TB91. Currently I'm still on TB78. I cannot tell an ETA as a lot of stuff is going on right now.

**Comment by kgraefe** [comment]
Also there seems to be an issue with FiltaQuilla that could be a blocker: https://github.com/RealRaven2000/FiltaQuilla/issues/128

**Comment by morda666** [comment]
Thank you :)

**Comment by kgraefe** [comment]
Closed by a93e771

**Comment by kgraefe** [comment]
It works for me now and I did not experience the FiltaQuilla issue. I used my TB78 profile and just upgraded it so the option stayed selected, though.

I wrote that script for myself, but it's always nice to hear that someone else is using it, too. Thanks for letting me know. ;-)
